import product01 from "../assets/product01.png";
import product02 from "../assets/product02.png";
import product03 from "../assets/product03.png";
import product04 from "../assets/product04.png";
import product05 from "../assets/product05.png";
import product06 from "../assets/product06.png";
import product07 from "../assets/product07.png";
import product08 from "../assets/product08.png";
import product09 from "../assets/product09.png";
import { IElectronicProduct } from "../interfaces/Product";

export const data: IElectronicProduct[] = [
  {
    id: 1,
    name: "Dell XPS 13",
    brand: "Dell",
    rating: 4,
    price: 1199.99,
    description: "A powerful and lightweight laptop for work and play",
    image: product01, //"https://example.com/dell-xps-13.jpg",
    stock: 25,
    salePercentage: 0,
    isNew: false,
    category: "Laptops",
    features: {
      screen: "13.4 inch FHD+",
      processor: "Intel Core i7-1165G7",
      ram: "16 GB",
      storage: "512 GB SSD",
      os: "Windows 10",
    },
    comments: [
      {
        comment:
          "Adoro o Dell XPS 13, é tão leve e perfeito para viagens. As especificações são incríveis e definitivamente vale o preço!",
        date: new Date("2023-03-22T10:00:00Z"),
        name: "Sarah",
        rating: 5,
      },
      {
        comment:
          "Tenho usado o Dell XPS 13 para trabalho e tem sido uma ótima experiência. O processador é super rápido e a tela é cristalina.",
        date: new Date("2023-03-23T16:30:00Z"),
        name: "João",
        rating: 4,
      },
      {
        comment:
          "Comprei recentemente o Dell XPS 13 e estou impressionado com a qualidade. É rápido, elegante e os recursos são exatamente o que eu estava procurando.",
        date: new Date("2023-03-25T11:45:00Z"),
        name: "Emily",
        rating: 5,
      },
      {
        comment:
          "O Dell XPS 13 é um ótimo laptop, mas é um pouco caro. No entanto, as especificações valem a pena e é definitivamente um dispositivo de primeira linha.",
        date: new Date("2023-03-27T13:15:00Z"),
        name: "Marcos",
        rating: 4,
      },
    ],
  },
  {
    id: 2,
    name: "Fone Gamer",
    brand: "HyperX",
    rating: 4,
    price: 299.99,
    description: "Fone de ouvido gamer com microfone destacável",
    image: product02, //"https://example.com/hyperx-headset.jpg",
    stock: 5,
    salePercentage: 10,
    isNew: true,
    category: "Fones de ouvido",
    features: {
      type: "Over-ear",
      connectivity: "3.5mm Jack",
      impedance: "60 ohms",
      frequencyResponse: "15Hz-25KHz",
      sensitivity: "102 dB",
    },
  },
  {
    id: 3,
    name: "Notebook Dell Inspiron 15",
    brand: "Dell",
    rating: 4,
    price: 3899.99,
    description: "Notebook de alta performance, ideal para trabalho e lazer.",
    image: product03, //"https://images.com/dell-inspiron-15.jpg",
    stock: 10,
    salePercentage: 15,
    isNew: true,
    category: "Laptops",
    comments: [
      {
        name: "Alice",
        date: new Date("2022-03-10"),
        rating: 4,
        comment:
          "O notebook é rápido e muito leve, mas a bateria poderia durar mais tempo.",
      },
      {
        name: "Bob",
        date: new Date("2022-02-15"),
        rating: 5,
        comment:
          "Melhor notebook que já comprei! Tela incrível, teclado confortável e ótimo desempenho.",
      },
      {
        name: "Carol",
        date: new Date("2022-01-20"),
        rating: 3,
        comment:
          "O notebook é bom, mas não é tão poderoso quanto eu esperava. Ainda assim, recomendo para uso básico.",
      },
    ],
    features: {
      screen: "15.6 inches Full HD",
      processor: "Intel Core i7-10750H",
      ram: "16GB DDR4",
      storage: "512GB SSD",
      os: "Windows 10 Home",
    },
  },
  {
    id: 4,
    name: "Samsung Galaxy Tab S7+",
    brand: "Samsung",
    rating: 4,
    price: 6999,
    description:
      "Tablet com tela AMOLED de 12.4 polegadas, processador Snapdragon 865+ e 8GB de RAM.",
    image: product04, //"https://via.placeholder.com/300x300",
    stock: 10,
    salePercentage: 0,
    isNew: false,
    category: "Tablets",
    features: {
      screen: "12.4 polegadas, AMOLED, 1752 x 2800 pixels",
      processor: "Qualcomm Snapdragon 865+",
      ram: "8 GB",
      storage: "256 GB",
      os: "Android 11",
    },
  },
  {
    id: 5,
    name: "Sony WH-1000XM4",
    brand: "Sony",
    rating: 4,
    price: 1199.99,
    description:
      "Fone de ouvido com tecnologia de cancelamento de ruído para proporcionar a melhor experiência sonora possível. O design elegante e ergonômico garante o máximo conforto durante o uso prolongado. O microfone integrado permite atender chamadas e controlar a reprodução de música diretamente no fone. Conectividade Bluetooth para facilitar a conexão com outros dispositivos.",
    image: product05, //"https://example.com/sony-a7iii.jpg",
    stock: 10,
    salePercentage: 15,
    isNew: true,
    category: "Fones de ouvido",
    features: {
      type: "Over-ear",
      connectivity: "Bluetooth",
      impedance: "32 ohms",
      frequencyResponse: "4Hz-40KHz",
      sensitivity: "105 dB",
    },
  },
  {
    id: 6,
    name: "MSI GL75 Leopard",
    brand: "MSI",
    rating: 4,
    price: 1599.99,
    description: "A high-performance gaming laptop for serious gamers",
    image: product06, //"https://example.com/msi-gaming-laptop.jpg",
    stock: 10,
    salePercentage: 5,
    isNew: false,
    category: "Laptops",
    features: {
      screen: "17.3 inch FHD",
      processor: "Intel Core i7-10750H",
      ram: "16 GB DDR4",
      storage: "1 TB NVMe SSD",
      os: "Windows 10 Home",
    },
  },
  {
    id: 7,
    name: "Samsung Galaxy S21",
    brand: "Samsung",
    rating: 4,
    price: 499.99,
    description: "A powerful smartphone with a beautiful AMOLED display",
    image: product07, //"https://example.com/samsung-galaxy-s21.jpg",
    stock: 50,
    salePercentage: 10,
    isNew: true,
    category: "Smartphones",
    features: {
      screen: "6.2 inch AMOLED",
      processor: "Exynos 2100",
      ram: "8 GB",
      storage: "128 GB",
      os: "Android 11",
    },
  },
  {
    id: 8,
    name: "Notebook Asus Zenbook",
    brand: "Asus",
    rating: 4,
    price: 2499.99,
    description:
      "Um notebook elegante e potente, perfeito para trabalhar e estudar",
    image: product08, //"https://example.com/asus-zenbook.jpg",
    stock: 10,
    salePercentage: 15,
    isNew: true,
    category: "Laptops",
    features: {
      screen: "14 polegadas Full HD",
      processor: "Intel Core i7-1165G7",
      ram: "16 GB",
      storage: "512 GB SSD",
      os: "Windows 10 Home",
    },
  },
  {
    id: 9,
    name: "Câmera DSLR Canon EOS Rebel T7",
    brand: "Canon",
    rating: 4,
    price: 2199.99,
    description: "Câmera profissional para fotógrafos exigentes",
    image: product09, //"https://example.com/camera1.jpg",
    stock: 10,
    salePercentage: 15,
    isNew: false,
    category: "Câmeras",
    features: {
      screen: "3 polegadas",
      processor: "DIGIC 4+",
      ram: "",
      storage: "",
      os: "",
    },
  },
  {
    id: 10,
    name: "Câmera Mirrorless Sony Alpha a7 III",
    brand: "Sony",
    rating: 4,
    price: 7999.99,
    description: "Câmera profissional para fotógrafos exigentes",
    image: product09, //"https://example.com/camera2.jpg",
    stock: 5,
    salePercentage: 10,
    isNew: true,
    category: "Câmeras",
    features: {
      screen: "3 polegadas",
      processor: "BIONZ X",
      ram: "",
      storage: "",
      os: "",
    },
  },
  {
    id: 11,
    name: "Sony Alpha a7 III",
    brand: "Sony",
    rating: 4,
    price: 1999.99,
    description:
      "A full-frame mirrorless camera for professional photographers",
    image: product05, //"https://example.com/sony-a7iii.jpg",
    stock: 10,
    salePercentage: 20,
    isNew: true,
    category: "Câmeras",
    features: {
      screen: "3.0 inch LCD",
      processor: "BIONZ X",
      ram: "N/A",
      storage: "2 SD card slots",
      os: "Sony Alpha system software",
    },
  },
  {
    id: 13,
    name: "Câmera Fotográfica Lenovo",
    brand: "Lenovo",
    rating: 4,
    price: 899.99,
    description:
      "Uma câmera compacta e versátil para fotógrafos amadores e profissionais",
    image: "https://example.com/lenovo-camera.jpg",
    stock: 8,
    salePercentage: 5,
    isNew: false,
    category: "Câmeras Fotográficas",
    features: {
      resolution: "24.2 megapixels",
      sensor: "APS-C",
      isoRange: "100-25600",
      videoResolution: "Full HD 1080p",
      connectivity: "Wi-Fi, Bluetooth",
    },
  },
  {
    id: 14,
    name: "Lenovo ThinkPad X1 Carbon",
    brand: "Lenovo",
    rating: 4,
    price: 1499.99,
    description: "A high-performance business laptop with a durable design",
    image: "https://example.com/lenovo-thinkpad-x1-carbon.jpg",
    stock: 20,
    salePercentage: 5,
    isNew: false,
    category: "Laptops",
    features: {
      screen: "14 inch FHD",
      processor: "Intel Core i7-1165G7",
      ram: "16 GB",
      storage: "512 GB SSD",
      os: "Windows 10 Pro",
    },
  },
  {
    id: 15,
    name: "Apple iPad Pro",
    brand: "Apple",
    rating: 4,
    price: 8999,
    description:
      "Tablet com tela Liquid Retina XDR de 11 polegadas, chip M1 e 8GB de RAM.",
    image: product06, //"https://via.placeholder.com/300x300",
    stock: 20,
    salePercentage: 10,
    isNew: true,
    category: "Tablets",
    features: {
      screen: "11 polegadas, Liquid Retina XDR, 1668 x 2388 pixels",
      processor: "Apple M1",
      ram: "8 GB",
      storage: "256 GB",
      os: "iPadOS 14",
    },
  },
  {
    id: 16,
    name: "Fone de ouvido Bluetooth",
    brand: "Sony",
    rating: 4,
    price: 399.99,
    description: "Fone de ouvido Bluetooth com microfone integrado",
    image: "https://example.com/sony-headphones.jpg",
    stock: 10,
    salePercentage: 0,
    isNew: false,
    category: "Fones de ouvido",
    features: {
      type: "Intra-auricular",
      connectivity: "Bluetooth",
      impedance: "32 ohms",
      frequencyResponse: "20Hz-20KHz",
      sensitivity: "110 dB",
    },
  },
];

export const dataList = [
  {
    text: "Laptops",
    link: "/shop?c=laptops",
  },
  {
    text: "Smartphones",
    link: "/shop?c=smartphones",
  },
  {
    text: "Câmeras",
    link: "/shop?c=cameras",
  },
  {
    text: "Acessórios",
    link: "/shop?c=acessorios",
  },
];
