export default {
  cardWidthMobile: "100%",
  cardWidthTablet: "50%",
  cardWidthDesktop: "25%",
  paddingContainer: "0 2rem",
  cardMargin: "0 1rem",
  rosaclaro: "#ffc3c3",
  rosamedio: "#ff99cc",
  azulescuro: "#003366",
  azulmedio: "#009acd",
  azulclaro: "#00bfff",
  cinzaclaro: "#f0f0f0",
  cinzamedio: "#cccccc",
  draculaPurple: "#9580ff",
  branco: "#ffffff",
  preto: "#000000",
};
